services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.6
    container_name: hotel-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: hotel_reservations
      MARIADB_USER: hotel_user
      MARIADB_PASSWORD: hotel_password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      timeout: 20s
      retries: 10

  # Payara Server
  payara:
    build: .
    container_name: hotel-payara
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "4848:4848"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD-SHELL", "asadmin list-applications | grep -q '^hotel-reservation-management-system '"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 60s

  # Adminer (Database Management Tool)
  adminer:
    image: adminer:4.8.1
    container_name: hotel-adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - hotel-network

volumes:
  mariadb_data:
    driver: local

networks:
  hotel-network:
    driver: bridge